
/**
 This class creates the starting menu and controls all functions on that such
 as the music, which game mode is selected, opening the high scores and
 inputing the users name.

 @author Jake Ira
 @author Nick Sosinski
 */
import java.awt.*;

public class StartingGUI extends java.awt.Frame
{

   private final String[] COMMAND_ARGUMENTS = new String[1];
   private final String MENU_MUSIC = "Hello.wav";
   private final String GAME_MUSIC = "The Drift.wav";

   private HighScoreDataManagement highScoresDataManager;

   /**
    This constructor starts the games menu music and initializes components.
    */
   public StartingGUI()
   {
      highScoresDataManager = new HighScoreDataManagement();
      Sound.playGameMusic(MENU_MUSIC);
      initComponents();
   }

   /**
    This method is called from within the constructor to initialize the form.
    WARNING: Do NOT modify this code. The content of this method is always
    regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      scoresPanel = new java.awt.Panel();
      highScoreLabel = new java.awt.Label();
      scoreList = new java.awt.List();
      closeButton = new java.awt.Button();
      roundScoresButton = new java.awt.Button();
      survivalScoresButton = new java.awt.Button();
      titleLabel = new java.awt.Label();
      survivalButton = new java.awt.Button();
      roundsButton = new java.awt.Button();
      highScoresButton = new java.awt.Button();
      userNameTextField = new java.awt.TextField();
      label1 = new java.awt.Label();

      setBackground(java.awt.Color.red);
      setMaximumSize(new java.awt.Dimension(566, 416));
      setMinimumSize(new java.awt.Dimension(566, 416));
      setResizable(false);
      addWindowListener(new java.awt.event.WindowAdapter()
      {
         public void windowClosing(java.awt.event.WindowEvent evt)
         {
            exitForm(evt);
         }
      });
      setLayout(null);

      scoresPanel.setBackground(java.awt.Color.red);
      scoresPanel.setName("scoresPanel"); // NOI18N
      scoresPanel.setVisible(false);
      scoresPanel.setLayout(null);

      highScoreLabel.setAlignment(java.awt.Label.CENTER);
      highScoreLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
      highScoreLabel.setName("highScoreLabel"); // NOI18N
      highScoreLabel.setText("High Scores");
      scoresPanel.add(highScoreLabel);
      highScoreLabel.setBounds(0, 40, 560, 50);
      scoresPanel.add(scoreList);
      scoreList.setBounds(40, 90, 480, 280);

      closeButton.setActionCommand("closeButton");
      closeButton.setLabel("Close");
      closeButton.setName("closeButton"); // NOI18N
      closeButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            closeButtonActionPerformed(evt);
         }
      });
      scoresPanel.add(closeButton);
      closeButton.setBounds(240, 380, 49, 24);
      closeButton.getAccessibleContext().setAccessibleName("closeButton");

      roundScoresButton.setActionCommand("roundScoresButton");
      roundScoresButton.setLabel("Round Scores");
      roundScoresButton.setName("roundScoresButton"); // NOI18N
      roundScoresButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            roundScoresButtonActionPerformed(evt);
         }
      });
      scoresPanel.add(roundScoresButton);
      roundScoresButton.setBounds(40, 380, 90, 24);
      roundScoresButton.getAccessibleContext().setAccessibleName("roundScoresButton");

      survivalScoresButton.setActionCommand("survivalScoresButton");
      survivalScoresButton.setLabel("Survival Scores");
      survivalScoresButton.setName("survivalScoresButton"); // NOI18N
      survivalScoresButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            survivalScoresButtonActionPerformed(evt);
         }
      });
      scoresPanel.add(survivalScoresButton);
      survivalScoresButton.setBounds(430, 380, 90, 24);
      survivalScoresButton.getAccessibleContext().setAccessibleName("survivalScoresButton");

      add(scoresPanel);
      scoresPanel.setBounds(0, 0, 560, 410);

      titleLabel.setAlignment(java.awt.Label.CENTER);
      titleLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
      titleLabel.setName(""); // NOI18N
      titleLabel.setText("Cowboy ScanMan ");
      add(titleLabel);
      titleLabel.setBounds(10, 60, 550, 50);

      survivalButton.setLabel("Survival Mode");
      survivalButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            survivalButtonActionPerformed(evt);
         }
      });
      add(survivalButton);
      survivalButton.setBounds(70, 300, 90, 24);

      roundsButton.setLabel("Rounds");
      roundsButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            roundsButtonActionPerformed(evt);
         }
      });
      add(roundsButton);
      roundsButton.setBounds(70, 210, 90, 24);

      highScoresButton.setLabel("High Scores");
      highScoresButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            highScoresButtonActionPerformed(evt);
         }
      });
      add(highScoresButton);
      highScoresButton.setBounds(340, 300, 90, 24);

      userNameTextField.setText("Player Name");
      add(userNameTextField);
      userNameTextField.setBounds(340, 210, 90, 20);

      label1.setAlignment(java.awt.Label.CENTER);
      label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
      label1.setText("(for best experience turn on sound)");
      add(label1);
      label1.setBounds(0, 120, 570, 30);

      pack();
   }// </editor-fold>//GEN-END:initComponents

   /**
    Exit the Application

    @param evt The window event data (Not Used).
    */
    private void exitForm(java.awt.event.WindowEvent evt)//GEN-FIRST:event_exitForm
	{//GEN-HEADEREND:event_exitForm
      System.exit(0);
    }//GEN-LAST:event_exitForm

   /**
    This method prepares the game then starts it in survival mode, IF the
    player changed the player name. If they didn't, it changes the player name
    text box to yellow.

    @param evt The action event data (Not Used).
    */
   private void survivalButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_survivalButtonActionPerformed
   {//GEN-HEADEREND:event_survivalButtonActionPerformed
      if (userNameTextField.getText().equals("Player Name"))
         userNameTextField.setBackground(Color.yellow);
      else
      {
         prepGame();
         COMMAND_ARGUMENTS[0] = "survival";
         Prog5GUI.main(COMMAND_ARGUMENTS);
      }
   }//GEN-LAST:event_survivalButtonActionPerformed
   /**
    This method prepares the game then starts it in round mode, IF the player
    changed the player name. If they didn't, it changes the player name text
    box to yellow.

    @param evt The action event data (Not Used).
    */
   private void roundsButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_roundsButtonActionPerformed
   {//GEN-HEADEREND:event_roundsButtonActionPerformed
      if (userNameTextField.getText().equals("Player Name"))
         userNameTextField.setBackground(Color.yellow);
      else
      {
         prepGame();
         COMMAND_ARGUMENTS[0] = "rounds";
         Prog5GUI.main(COMMAND_ARGUMENTS);
      }
   }//GEN-LAST:event_roundsButtonActionPerformed
   /**
    This method the players name for high scores, stops the menu music, and
    starts the game music.
    */
   private void prepGame()
   {
      HighScoreDataManagement.setPlayerName(userNameTextField.getText());
      Sound.stopGameMusic();
      Sound.playGameMusic(GAME_MUSIC);
   }

   /**
    This method clears the list of scores, sets the scores panel to the
    visible then adds the scores for the rounds high scores.

    @param evt The action event data (Not Used).
    */
   private void highScoresButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_highScoresButtonActionPerformed
   {//GEN-HEADEREND:event_highScoresButtonActionPerformed
      highScoresDataManager = new HighScoreDataManagement();
      scoreList.removeAll();
      scoresPanel.setVisible(true);
      highScoresDataManager.addScoresToList(scoreList, "rounds");
   }//GEN-LAST:event_highScoresButtonActionPerformed

   /**
    This method sets the scores panel visible boolean to false then clears the
    list of scores.

    @param evt The action event data (Not Used).
    */
   private void closeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closeButtonActionPerformed
   {//GEN-HEADEREND:event_closeButtonActionPerformed
      scoresPanel.setVisible(false);
      scoreList.removeAll();
   }//GEN-LAST:event_closeButtonActionPerformed

   /**
    This method clears all the scores in the list then adds the scores for the
    rounds high scores.

    @param evt The action event data (Not Used).
    */
   private void roundScoresButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_roundScoresButtonActionPerformed
   {//GEN-HEADEREND:event_roundScoresButtonActionPerformed
      highScoresDataManager = new HighScoreDataManagement();
      scoreList.removeAll();
      highScoresDataManager.addScoresToList(scoreList, "rounds");
   }//GEN-LAST:event_roundScoresButtonActionPerformed

   /**
    This method clears all the scores in the list then adds the scores for the
    survival high scores.

    @param evt The action event data (Not Used).
    */
   private void survivalScoresButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_survivalScoresButtonActionPerformed
   {//GEN-HEADEREND:event_survivalScoresButtonActionPerformed
      highScoresDataManager = new HighScoreDataManagement();
      scoreList.removeAll();
      highScoresDataManager.addScoresToList(scoreList, "survival");

   }//GEN-LAST:event_survivalScoresButtonActionPerformed

   /**
    This method runs the starting GUI.

    @param args the command line arguments (not used).
    */
   public static void main(String args[])
   {
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new StartingGUI().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private java.awt.Button closeButton;
   private java.awt.Label highScoreLabel;
   private java.awt.Button highScoresButton;
   private java.awt.Label label1;
   private java.awt.Button roundScoresButton;
   private java.awt.Button roundsButton;
   private java.awt.List scoreList;
   private java.awt.Panel scoresPanel;
   private java.awt.Button survivalButton;
   private java.awt.Button survivalScoresButton;
   private java.awt.Label titleLabel;
   private java.awt.TextField userNameTextField;
   // End of variables declaration//GEN-END:variables
}
