
/**
 This file creates a GUI to interact with a simulation.

 @author Nick Sosisnki
 @author Jake Ira
 */
public class GuiSimulation extends java.awt.Frame
{

   private Simulation sim;

   /**
    Creates a new GuiSimulation form.
    */
   public GuiSimulation()
   {
      sim = new Simulation();
      initComponents();
      setIconImage(java.awt.Toolkit.getDefaultToolkit().getImage(
            getClass().getResource("favicon.png")));
   }

   /**
    This method is called from within the constructor to initialize the form.
    WARNING: Do NOT modify this code. The content of this method is always
    regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      arrivalButton = new javax.swing.JButton();
      completionButton = new javax.swing.JButton();
      incrementTimeButton = new javax.swing.JButton();
      currentTimeTextField = new javax.swing.JTextField();
      currentTimeLabel = new javax.swing.JLabel();
      currentCustomerLabel = new javax.swing.JLabel();
      numberWaitingLabel = new javax.swing.JLabel();
      currentCustomerTextField = new javax.swing.JTextField();
      numberWaitingTextField = new javax.swing.JTextField();
      averageWaitTextField = new javax.swing.JTextField();
      totalWaitTextField = new javax.swing.JTextField();
      peopleNoWaitTextField = new javax.swing.JTextField();
      averageWaitTimeLabel = new javax.swing.JLabel();
      totalWaitTimeLabel = new javax.swing.JLabel();
      peopleThatDidntWaitLabel = new javax.swing.JLabel();
      totalPeopleServedLabel = new javax.swing.JLabel();
      totalNumberServedTextField = new javax.swing.JTextField();
      updateStatisticsButton = new javax.swing.JButton();

      setMinimumSize(new java.awt.Dimension(400, 235));
      setResizable(false);
      setTitle("Program 4 - GUI");
      addWindowListener(new java.awt.event.WindowAdapter()
      {
         public void windowClosing(java.awt.event.WindowEvent evt)
         {
            exitForm(evt);
         }
      });
      setLayout(null);

      arrivalButton.setText("Arrival");
      arrivalButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            arrivalButtonActionPerformed(evt);
         }
      });
      add(arrivalButton);
      arrivalButton.setBounds(10, 40, 90, 23);

      completionButton.setText("Completion");
      completionButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            completionButtonActionPerformed(evt);
         }
      });
      add(completionButton);
      completionButton.setBounds(120, 40, 110, 23);

      incrementTimeButton.setText("Increment Time");
      incrementTimeButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            incrementTimeButtonActionPerformed(evt);
         }
      });
      add(incrementTimeButton);
      incrementTimeButton.setBounds(250, 40, 130, 23);

      currentTimeTextField.setEditable(false);
      currentTimeTextField.setText("0");
      add(currentTimeTextField);
      currentTimeTextField.setBounds(40, 90, 30, 20);

      currentTimeLabel.setText("Current Time");
      add(currentTimeLabel);
      currentTimeLabel.setBounds(20, 70, 100, 14);

      currentCustomerLabel.setText("Current Customer");
      add(currentCustomerLabel);
      currentCustomerLabel.setBounds(140, 70, 120, 14);

      numberWaitingLabel.setText("Number Waiting");
      add(numberWaitingLabel);
      numberWaitingLabel.setBounds(270, 70, 100, 14);

      currentCustomerTextField.setEditable(false);
      currentCustomerTextField.setText("none");
      add(currentCustomerTextField);
      currentCustomerTextField.setBounds(150, 90, 59, 20);

      numberWaitingTextField.setEditable(false);
      numberWaitingTextField.setText("0");
      add(numberWaitingTextField);
      numberWaitingTextField.setBounds(280, 90, 59, 20);

      averageWaitTextField.setEditable(false);
      averageWaitTextField.setText("0.0");
      averageWaitTextField.setToolTipText("");
      add(averageWaitTextField);
      averageWaitTextField.setBounds(130, 160, 70, 20);

      totalWaitTextField.setEditable(false);
      totalWaitTextField.setText("0");
      add(totalWaitTextField);
      totalWaitTextField.setBounds(130, 200, 70, 20);

      peopleNoWaitTextField.setEditable(false);
      peopleNoWaitTextField.setText("0");
      add(peopleNoWaitTextField);
      peopleNoWaitTextField.setBounds(350, 160, 30, 20);

      averageWaitTimeLabel.setText("Average Wait Time");
      add(averageWaitTimeLabel);
      averageWaitTimeLabel.setBounds(20, 160, 110, 14);

      totalWaitTimeLabel.setText("Total Wait Time");
      add(totalWaitTimeLabel);
      totalWaitTimeLabel.setBounds(20, 200, 90, 14);

      peopleThatDidntWaitLabel.setText("People That Didn't Wait");
      add(peopleThatDidntWaitLabel);
      peopleThatDidntWaitLabel.setBounds(210, 160, 170, 14);

      totalPeopleServedLabel.setText("Total People Served");
      add(totalPeopleServedLabel);
      totalPeopleServedLabel.setBounds(210, 200, 180, 14);

      totalNumberServedTextField.setEditable(false);
      totalNumberServedTextField.setText("0");
      add(totalNumberServedTextField);
      totalNumberServedTextField.setBounds(350, 200, 30, 20);

      updateStatisticsButton.setText("Update Statistics");
      updateStatisticsButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            updateStatisticsButtonActionPerformed(evt);
         }
      });
      add(updateStatisticsButton);
      updateStatisticsButton.setBounds(120, 120, 140, 23);

      pack();
   }// </editor-fold>//GEN-END:initComponents

   /**
    Exit the Application
    */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
       System.exit(0);
    }//GEN-LAST:event_exitForm

   /**
    This method requests for a customer to be added to the simulation. It also
    updates the number waiting and current customer text fields appropriately.

    @param evt The event information. (Not used)
    */
   private void arrivalButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_arrivalButtonActionPerformed
   {//GEN-HEADEREND:event_arrivalButtonActionPerformed
      Customer newCustomer = new Customer(sim.getTime());
      sim.addCustomer(newCustomer);
      numberWaitingTextField.setText(String.valueOf(sim.numWaiting()));
      currentCustomerTextField.setText(sim.curCustomer());
   }//GEN-LAST:event_arrivalButtonActionPerformed

   /**
    This method increments time in the simulation by 1. It also updates the
    time text field.

    @param evt The event information. (Not used)
    */
   private void incrementTimeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_incrementTimeButtonActionPerformed
   {//GEN-HEADEREND:event_incrementTimeButtonActionPerformed
      sim.advanceTime(1);
      currentTimeTextField.setText(String.valueOf(sim.getTime()));
   }//GEN-LAST:event_incrementTimeButtonActionPerformed

   /**
    This method requests for a customer to be served in the simulation. It
    also updates the number waiting and current customer text fields
    appropriately.

    @param evt The event information. (Not used)
    */
   private void completionButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_completionButtonActionPerformed
   {//GEN-HEADEREND:event_completionButtonActionPerformed
      if (sim.isHelpingCustomer())
      {
         sim.serveCustomer();
         numberWaitingTextField.setText(String.valueOf(sim.numWaiting()));
         currentCustomerTextField.setText(sim.curCustomer());
      }
   }//GEN-LAST:event_completionButtonActionPerformed

   /**
    This method updates the average wait time, total wait time, number of
    people that didn't have to wait, and total number of people served text
    fields appropriately.

    @param evt The event information. (Not used)
    */
   private void updateStatisticsButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_updateStatisticsButtonActionPerformed
   {//GEN-HEADEREND:event_updateStatisticsButtonActionPerformed
      averageWaitTextField.setText(
            Float.toString((float) sim.calculateAverageWait()));
      totalWaitTextField.setText(Integer.toString(sim.totalWaitTime()));
      peopleNoWaitTextField.setText(Integer.toString(sim.numWithNoWait()));
      totalNumberServedTextField.setText(Integer.toString(sim.numServed()));
   }//GEN-LAST:event_updateStatisticsButtonActionPerformed

   /**
    This method creates and runs an instance of GuiSimualtion.

    @param args The command line arguments passed in. (Not used in this
    program).
    */
   public static void main(String args[])
   {
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new GuiSimulation().setVisible(true);
         }
      });
   }


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton arrivalButton;
   private javax.swing.JTextField averageWaitTextField;
   private javax.swing.JLabel averageWaitTimeLabel;
   private javax.swing.JButton completionButton;
   private javax.swing.JLabel currentCustomerLabel;
   private javax.swing.JTextField currentCustomerTextField;
   private javax.swing.JLabel currentTimeLabel;
   private javax.swing.JTextField currentTimeTextField;
   private javax.swing.JButton incrementTimeButton;
   private javax.swing.JLabel numberWaitingLabel;
   private javax.swing.JTextField numberWaitingTextField;
   private javax.swing.JTextField peopleNoWaitTextField;
   private javax.swing.JLabel peopleThatDidntWaitLabel;
   private javax.swing.JTextField totalNumberServedTextField;
   private javax.swing.JLabel totalPeopleServedLabel;
   private javax.swing.JTextField totalWaitTextField;
   private javax.swing.JLabel totalWaitTimeLabel;
   private javax.swing.JButton updateStatisticsButton;
   // End of variables declaration//GEN-END:variables
}
