
import java.awt.event.ActionEvent;

/**

 @author Jake Ira
 @author Nick Sosinski
 */
public class My_Lab4_Frame extends java.awt.Frame implements java.awt.event.ActionListener
{

   private javax.swing.Timer moveTimer = new javax.swing.Timer(500, this);
   private final PicFig picfig;
   private final StickFig stickfig;

   /**
    Creates new form My_Lab4_Frame
    */
   public My_Lab4_Frame()
   {
      initComponents();
      setSize(550, 450);  // change numbers here if you don't like size
      picfig = new PicFig(figPanel);
      stickfig = new StickFig(figPanel);
      moveTimer.start();
   }

   /**
    This method is called from within the constructor to initialize the form.
    WARNING: Do NOT modify this code. The content of this method is always
    regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      figPanel = new java.awt.Panel();

      setMinimumSize(new java.awt.Dimension(500, 500));
      setTitle("Prog5Prop");
      addWindowListener(new java.awt.event.WindowAdapter()
      {
         public void windowClosing(java.awt.event.WindowEvent evt)
         {
            exitForm(evt);
         }
      });
      setLayout(null);

      figPanel.setName("figPanel"); // NOI18N
      add(figPanel);
      figPanel.setBounds(10, 30, 380, 260);

      pack();
   }// </editor-fold>//GEN-END:initComponents

   /**
    Exit the Application
    */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
       System.exit(0);
    }//GEN-LAST:event_exitForm

   /**
    @param args the command line arguments
    */
   public static void main(String args[])
   {
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new My_Lab4_Frame().setVisible(true);
         }
      });
   }

   @Override
   public void actionPerformed(ActionEvent ae)
   {
      picfig.hide();
      picfig.move();
      picfig.draw();
      stickfig.draw();
   }


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private java.awt.Panel figPanel;
   // End of variables declaration//GEN-END:variables
}
