
import java.awt.event.ActionEvent;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**

 @author Nick
 */
public class Prog5GUI extends java.awt.Frame implements java.awt.event.ActionListener
{
private final teddyFig Teddy;
private listOfPFigures figureList = new listOfPFigures();
private javax.swing.Timer moveTimer = new javax.swing.Timer(200, this);

   /**
    Creates new form Prog5GUI
    */
   public Prog5GUI()
   {
      initComponents();
      Teddy = new teddyFig(gamePanel);
      figureList.addFigure(Teddy);
      moveTimer.start();
   }

   /**
    This method is called from within the constructor to initialize the form.
    WARNING: Do NOT modify this code. The content of this method is always
    regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      gamePanel = new java.awt.Panel();
      clearAllFigs = new java.awt.Button();
      addFigure = new java.awt.Button();

      setMinimumSize(new java.awt.Dimension(500, 500));
      addWindowListener(new java.awt.event.WindowAdapter()
      {
         public void windowClosing(java.awt.event.WindowEvent evt)
         {
            exitForm(evt);
         }
      });
      setLayout(null);

      gamePanel.setBackground(new java.awt.Color(200, 200, 200));
      add(gamePanel);
      gamePanel.setBounds(20, 30, 360, 270);

      clearAllFigs.setActionCommand("clearAllFigs");
      clearAllFigs.setLabel("Clear All Figures");
      clearAllFigs.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            clearAllFigsActionPerformed(evt);
         }
      });
      add(clearAllFigs);
      clearAllFigs.setBounds(100, 310, 100, 24);

      addFigure.setActionCommand("addFig");
      addFigure.setLabel("Add Teddy");
      addFigure.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            addFigureActionPerformed(evt);
         }
      });
      add(addFigure);
      addFigure.setBounds(20, 310, 73, 24);

      pack();
   }// </editor-fold>//GEN-END:initComponents

   /**
    Exit the Application
    */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
       System.exit(0);
    }//GEN-LAST:event_exitForm

   private void clearAllFigsActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_clearAllFigsActionPerformed
   {//GEN-HEADEREND:event_clearAllFigsActionPerformed
      figureList.removeAllFigures();
   }//GEN-LAST:event_clearAllFigsActionPerformed

   private void addFigureActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_addFigureActionPerformed
   {//GEN-HEADEREND:event_addFigureActionPerformed
      figureList.addFigure(new teddyFig(gamePanel));
   }//GEN-LAST:event_addFigureActionPerformed

   /**
    @param args the command line arguments
    */
   public static void main(String args[])
   {
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new Prog5GUI().setVisible(true);
         }
      });
   }
   @Override
   public void actionPerformed(ActionEvent ae)
   {
      figureList.drawAll();
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private java.awt.Button addFigure;
   private java.awt.Button clearAllFigs;
   private java.awt.Panel gamePanel;
   // End of variables declaration//GEN-END:variables
}
