
/**

 @author Jake Ira
 @author Nick Sosinski
 */
import java.awt.*;

public class StartingGUI extends java.awt.Frame
{
   //*********************************TODO**********************************//
   //**************Add a username field for the leaderboard*****************//
   //*********************************TODO**********************************//

   private String[] commandString = new String[1];

   highScoreDataManagement highScores = new highScoreDataManagement();

   /**
    Creates new form StartingGUI
    */
   public StartingGUI()
   {
      Prog5GUI.playGameMusic("Hello.wav");
      initComponents();
   }

   public void closeGame()
   {
       
   }
   
   /**
    This method is called from within the constructor to initialize the form.
    WARNING: Do NOT modify this code. The content of this method is always
    regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      scoresPanel = new java.awt.Panel();
      highScoreLabel = new java.awt.Label();
      scoreList = new java.awt.List();
      closeButton = new java.awt.Button();
      roundScoresButton = new java.awt.Button();
      survivalScoresButton = new java.awt.Button();
      titleLabel = new java.awt.Label();
      survivalButton = new java.awt.Button();
      roundsButton = new java.awt.Button();
      highScoresButton = new java.awt.Button();
      userNameTextField = new java.awt.TextField();
      label1 = new java.awt.Label();

      setBackground(java.awt.Color.red);
      setMaximumSize(new java.awt.Dimension(566, 416));
      setMinimumSize(new java.awt.Dimension(566, 416));
      setResizable(false);
      addWindowListener(new java.awt.event.WindowAdapter()
      {
         public void windowClosing(java.awt.event.WindowEvent evt)
         {
            exitForm(evt);
         }
      });
      setLayout(null);

      scoresPanel.setBackground(java.awt.Color.red);
      scoresPanel.setName("scoresPanel"); // NOI18N
      scoresPanel.setVisible(false);
      scoresPanel.setLayout(null);

      highScoreLabel.setAlignment(java.awt.Label.CENTER);
      highScoreLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
      highScoreLabel.setName("highScoreLabel"); // NOI18N
      highScoreLabel.setText("High Scores");
      scoresPanel.add(highScoreLabel);
      highScoreLabel.setBounds(0, 40, 560, 50);
      scoresPanel.add(scoreList);
      scoreList.setBounds(40, 90, 480, 280);

      closeButton.setActionCommand("closeButton");
      closeButton.setLabel("Close");
      closeButton.setName("closeButton"); // NOI18N
      closeButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            closeButtonActionPerformed(evt);
         }
      });
      scoresPanel.add(closeButton);
      closeButton.setBounds(240, 380, 49, 24);
      closeButton.getAccessibleContext().setAccessibleName("closeButton");

      roundScoresButton.setActionCommand("roundScoresButton");
      roundScoresButton.setLabel("Round Scores");
      roundScoresButton.setName("roundScoresButton"); // NOI18N
      roundScoresButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            roundScoresButtonActionPerformed(evt);
         }
      });
      scoresPanel.add(roundScoresButton);
      roundScoresButton.setBounds(40, 380, 90, 24);
      roundScoresButton.getAccessibleContext().setAccessibleName("roundScoresButton");

      survivalScoresButton.setActionCommand("survivalScoresButton");
      survivalScoresButton.setLabel("Survival Scores");
      survivalScoresButton.setName("survivalScoresButton"); // NOI18N
      survivalScoresButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            survivalScoresButtonActionPerformed(evt);
         }
      });
      scoresPanel.add(survivalScoresButton);
      survivalScoresButton.setBounds(430, 380, 90, 24);
      survivalScoresButton.getAccessibleContext().setAccessibleName("survivalScoresButton");

      add(scoresPanel);
      scoresPanel.setBounds(0, 0, 560, 410);

      titleLabel.setAlignment(java.awt.Label.CENTER);
      titleLabel.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
      titleLabel.setName(""); // NOI18N
      titleLabel.setText("Cowboy ScanMan ");
      add(titleLabel);
      titleLabel.setBounds(10, 60, 550, 50);

      survivalButton.setLabel("Survival Mode");
      survivalButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            survivalButtonActionPerformed(evt);
         }
      });
      add(survivalButton);
      survivalButton.setBounds(70, 300, 90, 24);

      roundsButton.setLabel("Rounds");
      roundsButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            roundsButtonActionPerformed(evt);
         }
      });
      add(roundsButton);
      roundsButton.setBounds(70, 210, 90, 24);

      highScoresButton.setLabel("High Scores");
      highScoresButton.addActionListener(new java.awt.event.ActionListener()
      {
         public void actionPerformed(java.awt.event.ActionEvent evt)
         {
            highScoresButtonActionPerformed(evt);
         }
      });
      add(highScoresButton);
      highScoresButton.setBounds(340, 300, 90, 24);

      userNameTextField.setText("Player Name");
      add(userNameTextField);
      userNameTextField.setBounds(340, 210, 90, 20);

      label1.setAlignment(java.awt.Label.CENTER);
      label1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
      label1.setText("(for best experience turn on sound)");
      add(label1);
      label1.setBounds(0, 120, 570, 30);

      pack();
   }// </editor-fold>//GEN-END:initComponents

   /**
    Exit the Application
    */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
       System.exit(0);
    }//GEN-LAST:event_exitForm

   private void survivalButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_survivalButtonActionPerformed
   {//GEN-HEADEREND:event_survivalButtonActionPerformed
      if (userNameTextField.getText().equals("Player Name"))
         userNameTextField.setBackground(Color.yellow);
      else
      {
         Prog5GUI.setScoreName(userNameTextField.getText());
         Prog5GUI.stopGameMusic();
         Prog5GUI.playGameMusic("The Drift.wav");
         commandString[0] = "survival";
         Prog5GUI.main(commandString);
      }
   }//GEN-LAST:event_survivalButtonActionPerformed

   private void roundsButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_roundsButtonActionPerformed
   {//GEN-HEADEREND:event_roundsButtonActionPerformed
      if (userNameTextField.getText().equals("Player Name"))
         userNameTextField.setBackground(Color.yellow);
      else
      {
         Prog5GUI.stopGameMusic();
         Prog5GUI.playGameMusic("The Drift.wav");
         commandString[0] = "rounds";
         Prog5GUI.main(commandString);
      }
   }//GEN-LAST:event_roundsButtonActionPerformed

   private void highScoresButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_highScoresButtonActionPerformed
   {//GEN-HEADEREND:event_highScoresButtonActionPerformed
      scoresPanel.setVisible(true);
      highScores.addScoresToList(scoreList, "rounds");
   }//GEN-LAST:event_highScoresButtonActionPerformed

   private void closeButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_closeButtonActionPerformed
   {//GEN-HEADEREND:event_closeButtonActionPerformed
      scoresPanel.setVisible(false);
      scoreList.removeAll();
   }//GEN-LAST:event_closeButtonActionPerformed

   private void roundScoresButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_roundScoresButtonActionPerformed
   {//GEN-HEADEREND:event_roundScoresButtonActionPerformed
      scoreList.removeAll();
      highScores.addScoresToList(scoreList, "rounds");
   }//GEN-LAST:event_roundScoresButtonActionPerformed

   private void survivalScoresButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_survivalScoresButtonActionPerformed
   {//GEN-HEADEREND:event_survivalScoresButtonActionPerformed
      scoreList.removeAll();
      highScores.addScoresToList(scoreList, "survival");
      
   }//GEN-LAST:event_survivalScoresButtonActionPerformed

   /**
    @param args the command line arguments
    */
   public static void main(String args[])
   {
      java.awt.EventQueue.invokeLater(new Runnable()
      {
         public void run()
         {
            new StartingGUI().setVisible(true);
         }
      });
   }


   // Variables declaration - do not modify//GEN-BEGIN:variables
   private java.awt.Button closeButton;
   private java.awt.Label highScoreLabel;
   private java.awt.Button highScoresButton;
   private java.awt.Label label1;
   private java.awt.Button roundScoresButton;
   private java.awt.Button roundsButton;
   private java.awt.List scoreList;
   private java.awt.Panel scoresPanel;
   private java.awt.Button survivalButton;
   private java.awt.Button survivalScoresButton;
   private java.awt.Label titleLabel;
   private java.awt.TextField userNameTextField;
   // End of variables declaration//GEN-END:variables
}
